apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wil-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
        - name: wil-playground
          image: wil42/playground:v1
          
          ports:
            - containerPort: 8888
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: wil-playground-ingress-service
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - host: wil-playground.local
        path: /
        pathType: Prefix
        backend:
          service:
            name: wil-playground
            port:
              number: 8888
